version: "2"

services:
  base_build:
    build: "."
    image: stefanfoulis/timelapseapp-backend:local

  base: &BASE
    image: stefanfoulis/timelapseapp-backend:local
    depends_on:
      - "base_build"
      - "db"
      - "rabbitmq"
    command: bash
    env_file:
      - ".env-local"
      - ".env-local-secrets"
    volumes:
      - "timelapseapp-backend-src-sync:/app:rw"
      - "../timelapseapp-data:/data"

  web:
    <<: *BASE
    command: python manage.py runserver 0.0.0.0:80
    environment:
      VIRTUAL_HOST: timelapseapp-backend.divio.me

  worker:
    <<: *BASE
    command: aldryn-celery worker

  beat:
    <<: *BASE
    command: aldryn-celery beat

  cam:
    <<: *BASE
    command: aldryn-celery cam

  db:
    image: postgres:9.4
    volumes:
      - ".:/app:rw"
    environment:
      POSTGRES_DB: db

  rabbitmq:
    image: rabbitmq:3.5-management
    hostname: rabbitmq
    expose:
      - "15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret cookie here"
      VIRTUAL_HOST: "timelapseapp-rabbitmq.divio.me"
      VIRTUAL_PORT: 15672


volumes:
  timelapseapp-backend-src-sync:
    external: true
