version: "2"

services:
  baseimg:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: stefanfoulis/timelapse-manager:base-0.5
    command: bash
    volumes:
      - ".:/app:rw"
      - "./data:/data:rw"

  base:
    build: .
    image: timelapsemanager_base
    command: bash
    volumes:
      - ".:/app:rw"
      - "./data:/data:rw"
      - "/Volumes/Timelapse/images:/data/media/timelapse-images:rw"
    env_file: .env-local
    entrypoint: ["/tini", "--", ]

  web:
    extends: base
    image: timelapsemanager_base
    build: ""
    ports:
      - "49893:80"
    command: python manage.py runserver 0.0.0.0:80
    environment:
      VIRTUAL_HOST: timelapse-manager.aldryn.me

  worker:
    extends: base
    image: timelapsemanager_base
    build: ""
    command: aldryn-celery worker

  beat:
    extends: base
    image: timelapsemanager_base
    build: ""
    command: aldryn-celery beat

  cam:
    extends: base
    image: timelapsemanager_base
    build: ""
    command: aldryn-celery cam

  db:
    image: postgres:9.4
    volumes:
      - ".:/app:rw"
    environment:
      POSTGRES_DB: db

  rabbitmq:
    image: rabbitmq:3.5-management
    hostname: rabbitmq
    ports:
      - "35672:15672"
    expose:
      - "15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret cookie here"
      VIRTUAL_HOST: "radio-ch-rabbitmq.aldryn.me"
