# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-04 16:15
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields
import functools
import timelapse_manager.storage


class Migration(migrations.Migration):

    dependencies = [
        ('timelapse_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', max_length=255, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='image',
            name='scaled_at_160x120',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', max_length=255, null=True, upload_to=functools.partial(timelapse_manager.storage.upload_to_thumbnail, *(), **{b'size': '160x120'})),
        ),
        migrations.AlterField(
            model_name='image',
            name='scaled_at_320x240',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', max_length=255, null=True, upload_to=functools.partial(timelapse_manager.storage.upload_to_thumbnail, *(), **{b'size': '320x240'})),
        ),
        migrations.AlterField(
            model_name='image',
            name='scaled_at_640x480',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', max_length=255, null=True, upload_to=functools.partial(timelapse_manager.storage.upload_to_thumbnail, *(), **{b'size': '640x480'})),
        ),
    ]
