# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-20 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timelapse_manager', '0002_auto_20160320_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
                ('_updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='timelapse_manager.Camera')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_for_days', to='timelapse_manager.Image')),
                ('key_frames', models.ManyToManyField(blank=True, related_name='keyframe_for_days', to='timelapse_manager.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
