# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-05 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields
import functools
import timelapse_manager.storage


class Migration(migrations.Migration):

    dependencies = [
        ('timelapse_manager', '0003_auto_20160420_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, storage=timelapse_manager.storage.FileSystemTimelapseStorage(), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='image',
            name='scaled_at_160x120',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, storage=timelapse_manager.storage.FileSystemTimelapseStorage(), upload_to=functools.partial(timelapse_manager.storage.upload_to_thumbnail, *(), **{b'size': '160x120'})),
        ),
        migrations.AlterField(
            model_name='image',
            name='scaled_at_320x240',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, storage=timelapse_manager.storage.FileSystemTimelapseStorage(), upload_to=functools.partial(timelapse_manager.storage.upload_to_thumbnail, *(), **{b'size': '320x240'})),
        ),
        migrations.AlterField(
            model_name='image',
            name='scaled_at_640x480',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, storage=timelapse_manager.storage.FileSystemTimelapseStorage(), upload_to=functools.partial(timelapse_manager.storage.upload_to_thumbnail, *(), **{b'size': '640x480'})),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='movies', to='timelapse_manager.TagInfo'),
        ),
        migrations.AlterField(
            model_name='taginfo',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set([('camera', 'shot_at')]),
        ),
    ]
