# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields
import functools
import timelapse_manager.storage


class Migration(migrations.Migration):

    dependencies = [
        ('timelapse_manager', '0004_auto_20160505_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('shot_at',)},
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='original',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', max_length=255, null=True, storage=timelapse_manager.storage.FileSystemTimelapseStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='scaled_at_160x120',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', max_length=255, null=True, storage=timelapse_manager.storage.FileSystemTimelapseStorage(), upload_to=functools.partial(timelapse_manager.storage.upload_to_thumbnail, *(), **{'size': '160x120'})),
        ),
        migrations.AlterField(
            model_name='image',
            name='scaled_at_320x240',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', max_length=255, null=True, storage=timelapse_manager.storage.FileSystemTimelapseStorage(), upload_to=functools.partial(timelapse_manager.storage.upload_to_thumbnail, *(), **{'size': '320x240'})),
        ),
        migrations.AlterField(
            model_name='image',
            name='scaled_at_640x480',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', max_length=255, null=True, storage=timelapse_manager.storage.FileSystemTimelapseStorage(), upload_to=functools.partial(timelapse_manager.storage.upload_to_thumbnail, *(), **{'size': '640x480'})),
        ),
        migrations.AlterField(
            model_name='image',
            name='shot_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movierendering',
            name='file',
            field=models.FileField(blank=True, default='', max_length=255, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together=set([('camera', 'date')]),
        ),
    ]
