# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields
import functools
import timelapse_manager.storage


class Migration(migrations.Migration):

    dependencies = [
        ('timelapse_manager', '0005_auto_20160515_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='original_md5',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='image',
            name='scaled_at_160x120_md5',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='image',
            name='scaled_at_320x240_md5',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='image',
            name='scaled_at_640x480_md5',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, storage=timelapse_manager.storage.default_timelapse_storage, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='image',
            name='scaled_at_160x120',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, storage=timelapse_manager.storage.default_timelapse_storage, upload_to=functools.partial(timelapse_manager.storage.upload_to_thumbnail, *(), **{b'size': '160x120'})),
        ),
        migrations.AlterField(
            model_name='image',
            name='scaled_at_320x240',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, storage=timelapse_manager.storage.default_timelapse_storage, upload_to=functools.partial(timelapse_manager.storage.upload_to_thumbnail, *(), **{b'size': '320x240'})),
        ),
        migrations.AlterField(
            model_name='image',
            name='scaled_at_640x480',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, storage=timelapse_manager.storage.default_timelapse_storage, upload_to=functools.partial(timelapse_manager.storage.upload_to_thumbnail, *(), **{b'size': '640x480'})),
        ),
    ]
