# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields
import functools
import timelapse_manager.storage


class Migration(migrations.Migration):

    dependencies = [
        ('timelapse_manager', '0006_auto_20160605_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierendering',
            name='size',
            field=models.CharField(choices=[('640x480', '640x480'), ('320x240', '320x240'), ('160x120', '160x120')], default='160x120', max_length=32),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='original',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, db_index=True, default='', max_length=255, null=True, storage=timelapse_manager.storage.S3TimelapseStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='original_md5',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='image',
            name='scaled_at_160x120',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, db_index=True, default='', max_length=255, null=True, storage=timelapse_manager.storage.S3TimelapseStorage(), upload_to=functools.partial(timelapse_manager.storage.upload_to_thumbnail, *(), **{'size': '160x120'})),
        ),
        migrations.AlterField(
            model_name='image',
            name='scaled_at_160x120_md5',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='image',
            name='scaled_at_320x240',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, db_index=True, default='', max_length=255, null=True, storage=timelapse_manager.storage.S3TimelapseStorage(), upload_to=functools.partial(timelapse_manager.storage.upload_to_thumbnail, *(), **{'size': '320x240'})),
        ),
        migrations.AlterField(
            model_name='image',
            name='scaled_at_320x240_md5',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='image',
            name='scaled_at_640x480',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, db_index=True, default='', max_length=255, null=True, storage=timelapse_manager.storage.S3TimelapseStorage(), upload_to=functools.partial(timelapse_manager.storage.upload_to_thumbnail, *(), **{'size': '640x480'})),
        ),
        migrations.AlterField(
            model_name='image',
            name='scaled_at_640x480_md5',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
