# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timelapse_manager', '0008_movierendering_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
                ('_updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('realtime_timestamp', models.DateTimeField()),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='timelapse_manager.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('start_at', 'end_at')},
        ),
        migrations.RemoveField(
            model_name='movierendering',
            name='duration',
        ),
        migrations.AddField(
            model_name='frame',
            name='movie_rendering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='timelapse_manager.MovieRendering'),
        ),
    ]
