# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelapse_manager', '0010_auto_20160609_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='auto_resize_original',
            field=models.BooleanField(default=False, help_text='if enabled, every original image submitted through the imageintake will automatically be resized.'),
        ),
    ]
